<?php

namespace App\Models;

use CodeIgniter\Model;

class AnggotaModel extends Model
{
  protected $table      = 'data_reg_anggota';
  protected $primaryKey = 'no';

  protected $useAutoIncrement = false;

  protected $returnType     = 'object';
  protected $useSoftDeletes = false;

  protected $allowedFields = [
     'nik',
     'nama',
     'gelar1',
     'gelar2',
     'tmpt_lahir',
     'tgl_lahir',
     'jk',
     'alamat_1',
     'rt',
     'rw',
     'desa',
     'kec',
     'kab',
     'provinsi',
     'agama',
     'stat_kwn',
     'hp1',
     'hp2',
     'mail',
     'fb',
     'tw',
     'kerja',
     'jenis_tmpt_kerja',
     'nama_kerja1',
     'alamat_kerja1',
     'kerja2',
     'alamat_kerja2',
     'jab1',
     'jab2',
     'jab3',
     'gol',
     'tmt_gol',
     'str',
     'tmt_str',
     'sip1',
     'tmt_sip1',
     'sip2',
     'tmt_sip2',
     'sip3',
     'tmt_sip3',
     'sip4',
     'tmt_sip4',
     'thn_sprg',
     'ijazah_sprg',
     'tgl_sprg',
     'kampus_sprg',
     'thn_d3',
     'ijazah_d3',
     'tgl_d3',
     'kampus_d3',
     'linear_d4',
     'prodi_d4',
     'thn_d4',
     'ijazah_d4',
     'tgl_d4',
     'kampus_d4',
     'liniar_s2',
     'prodi_s2',
     'thn_s2',
     'ijazah_s2',
     'tgl_s2',
     'kampus',
     'dpd',
     'dpc',
     'usern',
     'pasw',
     'recover_quest',
     'recover_answ',
     'source',
     'status',
     'tgl_entry',
     'ibu_kandung',
     'no_kta',
     'tgl_berlaku',
     'photo',
     'dok_ktp',
     'dok_str',
     'dok_sip1',
     'dok_sip2',
     'dok_sip3',
     'dok_sip3',
     'dok_ijazah_sprg',
     'dok_ijazah_d3',
     'dok_ijazah_d4_s1',
     'dok_ijazah_s2',
     'dok_ijazah_s3',
     'level',
     'ssp',
     'dok_ssp',
     'kd_print_kta',
     'alasan_nonaktif',
     'penghasilan',
     'alamatm',
     'dpcm',
     'dpdm',
     'alasanm',
     'stsm',
     'zona',
     'praktik',
     'tipe_iurandpc',
     'verivikator',
     'catatan_anggota',
     'catatan',
     'csts',
     'ctgl',
     'provinsi_tempat_kerja',
     'kab_tempat_kerja',
     'tgl_gabung',
     'kode_aktivasi',
     'tgl_sts_aktivasi',
     'i_2019',
     'i_now',
     'i_pangkal',
     'i_gedung',
     'aktivasi',
     'tat_str',
     'mail_ptgmi',
     'no_sk_jf',
     'sk_jf',
     'kec_tempatkerja',
     'no_bpjs',
     'umr'




     

 ];

  protected bool $allowEmptyInserts = false;
  protected bool $updateOnlyChanged = true;
}